Sprint 4
prince-lvov/middle.messenger.praktikum.yandex pull request #10
Opened 2021-12-12 18:42 UTC by prince-lvov

Уважаемый, ревьювер. Отправляю работу 4 спринта, в которой сделан переход на Webpack, разобрался с подключениями плагинов и лоадеров, работой со статикой и стилями. На удаленном сервере с Ubuntu собрал и запустил Docker, куда положил node:12-alpine для уменьшения размера образа. Все это дело запушил на Heroku. 
Залетаю, наверняка как и другие, в последний вагон уходящего поезда с 5 спринтом| новым приложением |командной работой| новыми знаниями, поэтому очень надеюсь, что работа пройдет, так как сегодня крайний день сдачи. Времени и сил было потрачено много, но результатом более чем доволен. Благодарю Вас и Ваших коллег за аргументированные замечания, наставления и поддержку во время этих 4 спринтов.
https://my-lvov-finish.herokuapp.com

2021-12-12 19:22 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, проект выглядит очень не плохо, много интересных решений. Но есть проблемы с надежностью этого кода, в виду отсутствия честных типов и каких-либо обработчиков ошибок для асинхронных функций. Давайте попробуем это исправить:

- избавиться от `any`, в этом проекте практически нет мест, где бы они пригодились;
- добавить обработчики ошибок. Cейчас можно обойтись просто логированием в консоль причины ошибки;

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ChatPage/ChatPageApi.ts
> +        getUser().then(getChats).then(function () {
В колбеках принято использовать стрелочные функции:

`then(() => {});`

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ChatPage/ChatPageApi.ts
> +                    if (data.status !== 200) {
Эту логику можно вынести в базовый класс HTTP и проверять xhr.status, что бы не писать эту проверку 1000 раз

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ChatPage/ChatPageApi.ts
> +            .then(
На асинхронные функции стоит жобавть обработчики ошибок:

- `try{}catch`, если это async функции;
- `catch`, если идет работа с обычными промисами;

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ChatPage/InitSubmenu.ts
> +                const popup: any = document.querySelector('.chat-action-popup')
Так делать не стоит [querySelector](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelector#возвращаемое_значение), может вернуть null, тогда на следующей строчке ваш код упадет, TS об этом подсказывает, правильное решение это проблемы:
```

const popup = document.querySelector('.chat-action-popup');

if (popup) {
    // do smth
}
```

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ChatPage/Popup.ts
> +                            //@ts-ignore
В комментарии выше, я описал правильный способо решения подобных проблем, `@ts-ignore`, тут не выход - это потенциальная ошибка в рантайме;

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ProfilePage/ProfilePage.ts
> +                    //Router.get().to('/messenger')
Если этот код не нужен, его стоит удалить, а не закомментировать

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/components/ProfilePage/ProfilePageApi.ts
> +    const user = state.user as any
Тут нужен не any, а доказать по типам, что такое значение существует

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/my_core/WebSocket.ts
> +        //@ts-ignore
Зачем тут `ts-ignore`?

2021-12-12 19:22 UTC, DmitryKhitrin commented on src/my_core/core.ts
> +    user: any,
Тут везде тоже не any, давайте напишем корректные типы)

2021-12-14 09:28 UTC, prince-lvov commented on src/components/ChatPage/ChatPageApi.ts
> +        getUser().then(getChats).then(function () {
![image](https://user-images.githubusercontent.com/85033131/145971042-a7756754-a8dc-4c0f-9108-f45cbfd4415f.png)

2021-12-14 09:31 UTC, prince-lvov commented on src/components/ChatPage/ChatPageApi.ts
> +        getUser().then(getChats).then(function () {
А вот здесь сразу использовал стрелочную.

![image](https://user-images.githubusercontent.com/85033131/145971342-3f2eebde-e069-43cc-9b9b-cb810eb78ddd.png)

2021-12-14 09:52 UTC, prince-lvov commented on src/components/ProfilePage/ProfilePage.ts
> +                    //Router.get().to('/messenger')
Удалил.

2021-12-14 11:23 UTC, prince-lvov commented on src/components/ProfilePage/ProfilePageApi.ts
> +    const user = state.user as any
![image](https://user-images.githubusercontent.com/85033131/145989310-c9fe259f-023b-4967-b1ef-31edf20015ea.png)

2021-12-14 11:58 UTC, prince-lvov commented on src/components/ChatPage/InitSubmenu.ts
> +                const popup: any = document.querySelector('.chat-action-popup')
Поправил.
![image](https://user-images.githubusercontent.com/85033131/145994033-db19ad93-8f66-49bb-8a73-f71d6fbb2d5f.png)

2021-12-14 12:02 UTC, prince-lvov commented on src/components/ChatPage/Popup.ts
> +                            //@ts-ignore
Исправил.

![image](https://user-images.githubusercontent.com/85033131/145994729-55c67ca0-3e1a-4b5d-a298-82e1bf028267.png)

2021-12-14 12:04 UTC, prince-lvov commented on src/my_core/WebSocket.ts
> +        //@ts-ignore
Убрал, объявив тип по-честному.

![image](https://user-images.githubusercontent.com/85033131/145994918-7f476e43-a064-46eb-82f4-157d2e05be4b.png)

2021-12-14 12:07 UTC, prince-lvov commented on src/my_core/core.ts
> +    user: any,
Описал все типы в types.ts. Все any устранил.

![image](https://user-images.githubusercontent.com/85033131/145995346-c75bdd11-26bc-4138-9454-c8dce784713e.png)

2021-12-14 12:08 UTC, prince-lvov commented on src/components/ChatPage/ChatPageApi.ts
> +                    if (data.status !== 200) {
Сказано - сделано.

![image](https://user-images.githubusercontent.com/85033131/145995539-4767a441-5552-4463-ae45-ac90b4c4503e.png)

2021-12-14 12:10 UTC, prince-lvov commented on src/components/ChatPage/ChatPageApi.ts
> +            .then(
Добавил обработчики ошибок:

![image](https://user-images.githubusercontent.com/85033131/145995735-4156a81a-9d8d-4fa7-9b90-a616795b8d89.png)

2021-12-15 07:55 UTC, DmitryKhitrin approved these changes

2021-12-15 11:30 UTC, merged