Sprint 2
prince-lvov/middle.messenger.praktikum.yandex pull request #8
Opened 2021-06-27 19:32 UTC by prince-lvov

2021-06-28 21:26 UTC, avdoshenkov requested changes
В целом всё хорошо, молодец! И TS использован как надо, и в плане функций в порядке, и по вёрстке

Заметил только, что нет разделения по компонентам и страницам, как того требует задание. И остались ещё различные хелперы, которые не переведены на TS. Вот это всё поправить, и будет отлично 👍

2021-06-28 21:26 UTC, avdoshenkov commented on pug/templates/chat-page.pug
> +	.chat-messages--input-area
Этот элемент лучше сделать формой, т.к. тут есть сбор и отправка данных

2021-06-28 21:26 UTC, avdoshenkov commented on pug/templates/chat-page.pug
> +		.arrow
А этот — кнопкой с типом `submit`

2021-06-28 21:26 UTC, avdoshenkov commented on pug/templates/register_form.pug
> +                    input(type="text" name="name" id="name" autofocus)
Всем `input` в форме хорошо было бы добавить атрибут `id`, а лейблам — [`for`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for), для связки с конкретным полем ввода каждого заголовка

2021-06-29 04:36 UTC, prince-lvov commented on js/HTTPTransport/autor's_fetch.ts
> +function queryStringify(data: IHeaders) {
![image](https://user-images.githubusercontent.com/85033131/123738001-ad653e00-d8ac-11eb-8c4b-46375bfc3e03.png)
Добавил.

2021-06-29 04:48 UTC, prince-lvov commented on js/HTTPTransport/autor's_fetch.ts
> +    if (typeof data !== 'object') {
![image](https://user-images.githubusercontent.com/85033131/123738862-4e082d80-d8ae-11eb-89ac-cdac127b111d.png)
Уточнил проверку.

2021-06-29 04:52 UTC, prince-lvov commented on js/HTTPTransport/autor's_fetch.ts
> +class HTTPTransport {
![image](https://user-images.githubusercontent.com/85033131/123739175-e30b2680-d8ae-11eb-9b52-fdd525a86530.png)
Спасибо, так и сделал.

2021-06-29 05:28 UTC, prince-lvov commented on js/example/example.ts
> +function buttonClickHandler(this: BlockClass, event: Event) {
Принято. Example.ts файл вообще удалил, он был для тренировок.

2021-06-29 05:29 UTC, prince-lvov commented on js/includes/BlockClass.ts
> +		if (typeof parent == 'string') {
Абсолютно точно.

2021-06-29 07:21 UTC, prince-lvov commented on js/includes/ValidatorClass.ts
> +		return output
![image](https://user-images.githubusercontent.com/85033131/123754587-bca3b600-d8c3-11eb-9f08-040e17a57c08.png)
Действительно красивее получается)

2021-06-29 07:41 UTC, prince-lvov commented on js/includes/validationConditions.ts
> +		errorMessage: 'Пароль должен содержать хотя бы одну цифру, одну строчную и одну прописную букву'
![image](https://user-images.githubusercontent.com/85033131/123757287-7c920280-d8c6-11eb-9301-c368942410fd.png)
Убрал из регулярки Кириллицу и поправил текст ошибки

2021-06-29 08:23 UTC, prince-lvov commented on pug/templates/chat-page.pug
> +		.arrow
![image](https://user-images.githubusercontent.com/85033131/123763369-60915f80-d8cc-11eb-8228-512746ce7c88.png)
Явно указал тип кнопки submit на всякий случай. Хотя он такой по-умолчанию.

2021-06-29 08:33 UTC, prince-lvov commented on pug/templates/register_form.pug
> +                    input(type="text" name="name" id="name" autofocus)
![image](https://user-images.githubusercontent.com/85033131/123764756-c03c3a80-d8cd-11eb-9d15-f389b34454c2.png)
Полезное замечание. Сделал и в register_form.pug, и в login_form.pug.

2021-06-29 08:53 UTC, prince-lvov commented on pug/templates/chat-page.pug
> +	.chat-messages--input-area
Принято.

2021-06-29 18:20 UTC, avdoshenkov commented on js/includes/ValidatorClass.ts
> +		return output
Через стрелочную функцию и деструктуризацию объекта можно вообще в одну строчку уместиться :)

2021-06-29 18:32 UTC, avdoshenkov requested changes
Из правок по самому коду всё поправлено, молодец! Одна мелочь только.

Но осталась невыполненным часть задания по разделению компонент и страниц на отдельные папки (притом подразумевается, что в одной директории находится всё, что отвечает за конкретный компонент или страницу, т.е. вёрстка и TS-скрипт)

2021-06-29 18:32 UTC, avdoshenkov commented on pug/templates/chat-page.pug
> +		.arrow
Как раз для кнопки с вложением стоит указать тип `button`, а элемент с классом `arrow` вместо `div` переделать в кнопку с типом `submit`. Тогда, помимо прочего, например, если в поле ввода сообщения набрать текст и нажать на Enter, форма отправится

2021-07-06 07:18 UTC, avdoshenkov approved these changes
Хорошо! Только именно страницы лучше перенести в папку `pages` (создать в корне проекта), тогда будет, как в задании

И подумай, может стоит как-то избавиться от папки `pug`, а то для страницы логина, например, получается, что нужно помнить, что вёрстка в двух разных местах лежит. И локально у меня сейчас не получилось стартануть, потому что не находится файл `/pug/include/sidebar.pug`

В целом аппрувлю, но моменты, про которые выше написал, посмотри, пожалуйста. 
А вообще получается круто 👍

2021-07-06 07:18 UTC, avdoshenkov commented on components/ChatMessage/index.ts
> +	read: boolean,  // Флаг прочитанного сообщения
Булевы флаги лучше именовать более подробно, например, с добавлением глагола. Тогда гораздо лучше будет читаться, например, что конкретно это сообщение было прочитано каким-то пользователям, а не имеет/не имеет право на чтение в принципе. Вот [тут](https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig) неплохой разбор вопроса нейминга булевых флагов. Это так, на подумать на будущее)

2021-07-06 14:39 UTC, merged